name: Push to Feature Branch

on:
  push:
    branches-ignore:
      - prod
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2






      - name: Install
        shell: 'script -q -e -c "bash {0}"'
        run: make install
        env:
          FORCE_COLOR: 3
          CI: true
      - name: Test
        shell: 'script -q -e -c "bash {0}"'
        run: make test
        env:
          FORCE_COLOR: 3
          CI: true